globales:
  version: '@project.version@'
eureka:
  instance:
    instance-id: =${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: ${PORT:0}
spring:
  application:
    name: castores-service-remolques-inventarios
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER